#!/bin/sh
#
# @name Generic Tailsitter
#
# @type VTOL Duo Tailsitter
# @class VTOL
#
# @output MAIN1 motor right
# @output MAIN2 motor left
# @output MAIN5 elevon right
# @output MAIN6 elevon left
#
# @maintainer Roman Bapst <roman@px4.io>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults


param set-default VT_ELEV_MC_LOCK 0
param set-default VT_MOT_COUNT 4
param set-default VT_MOT_ID 1234
param set-default VT_TYPE 0

param set-default CBRK_AIRSPD_CHK 162128
param set-default FW_ARSP_MODE 1

set MAV_TYPE 19

set MIXER firefly6
set MIXER_AUX vtol_tailsitter_test

set PWM_OUT 1234
