#!/bin/sh
#
# @name Generic Tailsitter
#
# @type VTOL Duo Tailsitter
# @class VTOL
#
# @output MAIN1 motor right
# @output MAIN2 motor left
# @output MAIN5 elevon right
# @output MAIN6 elevon left
#
# @maintainer Roman Bapst <roman@px4.io>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults


param set-default VT_ELEV_MC_LOCK 0
param set-default VT_MOT_COUNT 2
param set-default VT_TYPE 0
# add FW_ARSP for test
param set-default FW_ARSP_MODE 1

param set-default MAV_TYPE 19
set MAV_TYPE 19

#ADD

set MIXER firefly6
set MIXER_AUX firefly6

set PWM_OUT 123456
