#!/bin/sh
#
# @name Y6 Tailsitter
#
# @type VTOL Duo Tailsitter
# @class VTOL
#
# @output MAIN1 motor right
# @output MAIN2 motor left
# @output MAIN5 elevon right
# @output MAIN6 elevon left
#
# @maintainer Roman Bapst <roman@px4.io>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default VT_MOT_COUNT 6
param set-default VT_FW_MOT_OFFID 3
param set-default VT_FW_MOT_OFFID 4
param set-default VT_IDLE_PWM_MC 1200
param set-default VT_TYPE 0
param set-default VT_B_TRANS_DUR 1.0
param set-default VT_FW_DIFTHR_EN 1
param set-default VT_FW_DIFTHR_SC 0.17
param set-default VT_FW_PERM_STAB 1
param set-default VT_F_TRANS_DUR 1.2
param set-default VT_F_TR_OL_TM 4.0
param set-default VT_TILT_FW 1.0
param set-default VT_TILT_MC 0.0
param set-default VT_TILT_TRANS 0.45
param set-default VT_TRANS_MIN_TM 1.2
param set-default VT_TRANS_P2_DUR 1.3
param set-default FW_ARSP_MODE 1

set MAV_TYPE 20

set MIXER quad_y6_vtol
set MIXER hexa_cox

set PWM_OUT 123456
